# Generated by Django 5.0.2 on 2024-02-23 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriesproduct',
            name='imagecategorie',
        ),
    ]
