# Generated by Django 5.0.2 on 2024-02-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blue', '0002_remove_categoriesproduct_imagecategorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(null='True', upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image4',
            field=models.ImageField(null='True', upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image5',
            field=models.ImageField(null='True', upload_to='product_images/'),
        ),
    ]
